type AccountType = {
    account_type_id: number;
    account_type_name: string;
    account_type_name_ar: string;
    account_type_name_en: string;
};

type Account = {
    account_id: string;
    account_type: AccountType;
    account_type_id: number;
    address_name: string | null;
    assigned_delegate_account: string | null;
    assigned_delegate_account_id: string | null;
    avatar_url: string | null;
    belong_to_agent_account: string | null;
    belong_to_agent_account_id: string | null;
    belong_to_merchant_account: string | null;
    belong_to_merchant_account_id: string | null;
    belong_to_owner_account: string | null;
    belong_to_owner_account_id: string | null;
    block_reason: string | null;
    blocked: boolean;
    blocked_at: string | null;
    branch_name: string | null;
    city: string | null;
    city_id: string | null;
    company_name: string | null;
    cr_image: string | null;
    cr_number: string | null;
    created_at: string;
    created_by_account_id: string | null;
    date_of_birth: string | null;
    deleted: boolean;
    deleted_at: string | null;
    district: string | null;
    district_id: string | null;
    email: string | null;
    full_name: string | null;
    gender: number | null;
    id_image: string | null;
    id_number: string | null;
    latitude: number | null;
    longitude: number | null;
    max_debt_limit: number;
    merchant_front_image: string | null;
    merchant_group: string | null;
    merchant_group_id: string | null;
    mobile: string;
    parent_merchant_account: string | null;
    parent_merchant_account_id: string | null;
    region: string | null;
    region_id: string | null;
    seq_id: number;
    total_balance: number;
    total_debt: number;
    updated_at: string;
    updated_by_account_id: string | null;
    vat_number: string | null;
};


export {Account, AccountType};